version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myblogdb
    networks:
      springboot-mysql-net:
  springboot-blog-app-restful-webservices:
    container_name: myblogapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net: